export const CONTRACT_ID = 'CBAMBILE2GHTSOMB7LX3YMBR2ZVW2G76QNZK375QFAICVGTUGAWDGCFW'
export const DEPLOYER_ADDRESS = 'GA5FHXZRASYTNPWAT3MJKX232ZG7NSQKQHVJQUX6V7SPWBPDUM2PQH6I'
export const NETWORK_PASSPHRASE = 'Test SDF Network ; September 2015'
export const RPC_URL = 'https://soroban-testnet.stellar.org'
export const HORIZON_URL = 'https://horizon-testnet.stellar.org'
